create table menu (
    id integer generated by default as identity ( START WITH 100 ),
    descrizione varchar(500),
    nazione varchar(100),
    nome varchar(100),
    primary key (id)
);

create table piatto (
    id integer generated by default as identity ( START WITH 100 ),
    menu_id integer not null references menu(id),
    nome varchar(100),
    costo float(53),
    disponibile boolean,
    descrizione varchar(255),
    primary key (id)
);